version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'nginx-container'
    image: nginx:1.19
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /var/log/letsencrypt/:/var/log/letsencrypt/:ro
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d/:ro
      - /etc/nginx/ssl:/etc/nginx/ssl/:ro
      - /var/www:/var/www:rw
      - /var/log/nginx:/var/log/nginx:rw
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
